name: CI/CD

on:
  push:
    branches: "**"
  workflow_dispatch:
      
jobs:

  lint:
    name: Lint source
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: "Lint"
        run: |
          git config --global user.name 'CI/CD'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npm run lint || true
          git commit -am "Eslint: fix all" || true
          git push origin ${{ github.head_ref }} || true

  version:
    name: Bump version
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bump Version
        run: |
          git config --global user.name 'CI/CD'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npm version patch -m "Bump: %s"
          git push origin ${{ github.head_ref }}

  docker-push:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: jmer05
          password: ${{ secrets.DOCKER_HUB }}

      - name: Build
        run: |
          docker build -t jmer05/ember .
      - name: Push
        run: |
          docker push jmer05/ember