name: CI/CD

on:
  push:
    branches: "**"
  workflow_dispatch:
      
jobs:

  source-changed:
    name: Did source change
    runs-on: ubuntu-latest
    outputs:
      has_applicable_changes: ${{ steps.check_for_changes.outputs.has_applicable_changes }}
    permissions:
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive
          fetch-depth: 0

      - name: Check for changes
        id: check_for_changes
        run: |
          echo "has_applicable_changes=$([[ $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E '.*\.(js|jsx|ts|tsx|json|less)' | wc -l) -gt 0 ]] && echo "true" || echo "false")" >> $GITHUB_OUTPUT

  lint:
    name: Lint source
    runs-on: ubuntu-latest
    needs: [ source-changed ]
    permissions:
      contents: write
    if: needs.source-changed.outputs.has_applicable_changes == 'true'
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: "Lint"
        run: |
          git config --global user.name 'CI/CD'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npm run lint || true
          git commit -am "Eslint: fix all" || true
          git push origin ${{ github.head_ref }} || true

  test:
    name: Test build
    runs-on: ubuntu-latest
    needs: [ source-changed ]
    if: needs.source-changed.outputs.has_applicable_changes == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: "Build"
        run: npm run build

      - name: "Test"
        run: npm run test

  codeql:
    name: Code quality scan
    needs: [ source-changed ]
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    if: needs.source-changed.outputs.has_applicable_changes == 'true'
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: true
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: "Build"
      run: npm run build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"

  version:
    name: Bump version
    runs-on: ubuntu-latest
    needs: [ test, codeql, lint ]
    if: github.ref != 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bump Version
        run: |
          git config --global user.name 'CI/CD'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npm version patch -m "Bump: %s"
          git push origin ${{ github.head_ref }}

  docker-push:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: [ test, codeql, lint ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: jmer05
          password: ${{ secrets.DOCKER_HUB }}

      - name: Build
        run: |
          docker build -t jmer05/ember .
      - name: Push
        run: |
          docker push jmer05/ember