name: CI/CD

on:
  push:
    branches: [ ember ]

jobs:

  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  docker-push:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: jmer05
          password: ${{ secrets.DOCKER_HUB }}

      - name: Build
        run: |
          docker build -t jmer05/ember .
      - name: Push
        run: |
          docker push jmer05/ember