name: Publish to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: jmer05
          password: ${{ secrets.DOCKER_HUB }}

      - name: Build
        run: |
          docker build -t jmer05/ember .
      - name: Push
        run: |
          docker push jmer05/ember